import re

__all__ = [
    'AUTHTOK_FORMAT',
    'DEEP_LOCALS',
    'FIRELOGGER_AUTH_HEADER',
    'FIRELOGGER_PROFILER_ENABLED',
    'FIRELOGGER_RESPONSE_HEADER',
    'FIRELOGGER_VERSION_HEADER',
    'JSONPICKLE_DEPTH',
    'RAZOR_MODE',
]

FIRELOGGER_VERSION_HEADER = 'HTTP_X_FIRELOGGER'
FIRELOGGER_AUTH_HEADER = 'HTTP_X_FIRELOGGERAUTH'
FIRELOGGER_PROFILER_ENABLED = 'HTTP_X_FIRELOGGERPROFILER'
FIRELOGGER_RESPONSE_HEADER = re.compile(r'^FireLogger', re.IGNORECASE)
FIRELOGGER_HEADER_FORMAT = 'FireLogger-%(guid)s-%(identity)s'
AUTHTOK_FORMAT = '#FireLoggerPassword#%s#'

DEEP_LOCALS = True
RAZOR_MODE = False
JSONPICKLE_DEPTH = 16
