import re

AUTHTOK_FORMAT = '#FireLoggerPassword#%s#'
DEEP_LOCALS = True
FIRELOGGER_APPSTATS_ENABLED_HEADER = 'HTTP_X_FIRELOGGERAPPSTATS'
FIRELOGGER_AUTH_HEADER = 'HTTP_X_FIRELOGGERAUTH'
FIRELOGGER_PROFILER_ENABLED = 'HTTP_X_FIRELOGGERPROFILER'
FIRELOGGER_RESPONSE_HEADER = re.compile(r'^FireLogger', re.IGNORECASE)
FIRELOGGER_VERSION_HEADER = 'HTTP_X_FIRELOGGER'
JSONPICKLE_DEPTH = 16
RAZOR_MODE = False
