#!/usr/bin/env ruby

require 'rubygems'

ROOT = File.expand_path('./..')
TMP = File.join(ROOT, 'tmp')
EXT = File.join(ROOT, 'extension')
SKIN = File.join(EXT, 'chrome', 'skin') 

OSX = PLATFORM =~ /darwin/
WIN = PLATFORM =~ /win32/
NIX = !(OSX || WIN)

# http://kpumuk.info/ruby-on-rails/colorizing-console-ruby-script-output/
begin
  require 'Win32/Console/ANSI' if WIN
rescue LoadError
  raise 'You must "sudo gem install win32console" to use terminal colors on Windows'
end

begin
  require 'rmagick'
  include Magick
rescue LoadError
  raise 'You must "sudo gem install rmagick"'
end

def colorize(text, color_code)
  "#{color_code}#{text}\e[0m"
end

def red(text); colorize(text, "\e[31m"); end
def green(text); colorize(text, "\e[32m"); end
def yellow(text); colorize(text, "\e[33m"); end
def blue(text); colorize(text, "\e[34m"); end
def magenta(text); colorize(text, "\e[35m"); end
def azure(text); colorize(text, "\e[36m"); end
def white(text); colorize(text, "\e[37m"); end
def black(text); colorize(text, "\e[30m"); end

def convert_to_grayscale(mask, prefix="gray-", postfix="")
  Dir.glob(mask).each do |fn|
    next unless File.file?(fn)
    dn = File.join(File.dirname(fn), prefix+File.basename(fn, ".*")+postfix+File.extname(fn))
    puts green("  #{File.basename(fn)} -> #{File.basename(dn)}")
    image = ImageList.new(fn)
    r = image.quantize(256, GRAYColorspace)
    r.write(dn)
  end
end

def convert_to_hover(mask, prefix="hover-", postfix="")
  Dir.glob(mask).each do |fn|
    next unless File.file?(fn)
    dn = File.join(File.dirname(fn), prefix+File.basename(fn, ".*")+postfix+File.extname(fn))
    puts green("  #{File.basename(fn)} -> #{File.basename(dn)}")
    image = ImageList.new(fn)
    r = image.level(0, 1.8)
    r.write(dn)
  end
end

#----------------------------------------------------------------------------
desc "renders grayscale version of graphics"
task :convert do
  convert_to_grayscale(File.join(SKIN, "icon*"), "disabled-")
  convert_to_hover(File.join(SKIN, "icon*"), "hover-")
  convert_to_grayscale(File.join(SKIN, "hover-icon*"), "disabled-")
end

#----------------------------------------------------------------------------
task :default => :convert